# Generated by Django 5.0 on 2024-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='ID платежа'),
        ),
    ]
