# Generated by Django 5.0 on 2024-07-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='ID платежа'),
        ),
    ]
